[package]
name = "manifold"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

nalgebra = "0.33.2"
nalgebra-sparse = "0.10.0"

indexmap = "2.8.0"
itertools = "0.14.0"
tracing = "0.1.41"

mshio = "0.4.2"
approx = "0.5.1"
rayon = "1.10.0"
