[package]
name = "manifold"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

nalgebra = "0.33.2"
nalgebra-sparse = "0.10.0"

indexmap = "2.7.0"
itertools = "0.13.0"
tracing = "0.1.40"

mshio = "0.4.2"
vtkio = "0.6.3"
