[package]
name = "formoniq"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.1"
nalgebra-sparse = "0.10.0"
faer = "0.19.4"

mshio = "0.4.2"

indexmap = "2.6.0"
once_cell = "1.20.2"
thiserror = "1.0.65"
tracing = "0.1.40"
num-integer = "0.1.46"
itertools = "0.13.0"
num-traits = "0.2.19"

[dev-dependencies]
tracing-subscriber = "0.3.18"

