[package]
name = "formoniq"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
nalgebra-sparse = "0.10.0"
faer = "0.19.1"

mshio = "0.4.2"

indexmap = "2.2.6"
once_cell = "1.19.0"
thiserror = "1.0.62"
tracing = "0.1.40"
num-integer = "0.1.46"
itertools = "0.13.0"

[dev-dependencies]
tracing-subscriber = "0.3.18"


