[package]
name = "formoniq"
version = "0.1.0"
edition = "2021"

[dependencies]
faer = "0.19.1"
itertools = "0.13.0"
mshio = "0.4.2"
nalgebra = "0.33.0"
nalgebra-sparse = "0.10.0"
once_cell = "1.19.0"
thiserror = "1.0.62"
tracing = "0.1.40"

[dev-dependencies]
tracing-subscriber = "0.3.18"

