[package]
name = "topology"
version = "0.1.0"
edition = "2021"

[dependencies]
index-algebra = { path = "../index-algebra" }
common = { path = "../common" }

nalgebra = "0.33.2"

indexmap = "2.7.0"
itertools = "0.13.0"
