//! Integer simplicial homology of the complex.
//!
//! The Betti numbers $b_k = dim H_k (K; ZZ)$ of the chain complex
//!
//! $dots.c ->^(partial_(k+1)) C_k ->^(partial_k) C_(k-1) ->^(partial_(k-1)) dots.c$
//!
//! read off the ranks of the (integer) boundary operators:
//!
//! $b_k = dim ker partial_k - rank partial_(k+1) = n_k - rank partial_k - rank partial_(k+1)$,
//!
//! with $n_k$ the number of k-simplices. Metric-free (invariant 5): homology is
//! a topological invariant, a function of the incidence alone.
//!
//! Everything here is exact, over $ZZ$ and $QQ$ rather than over $RR$ with a
//! tolerance, and the arithmetic that makes it so is
//! the crate-internal exact integer linear algebra. The full torsion of $H_k (K; ZZ)$
//! is not recovered: it is invisible to the de Rham / Hodge side of the
//! library, which lives over $RR$, so only the free rank is returned.
//!
//! [`cohomology`](super::cohomology) is the same computation on the transposed
//! incidence.

use super::{chain::Chain, complex::Complex};
use crate::Dim;
use crate::linalg::exact::quotient_generators;

impl Complex {
  /// The Betti numbers $b_0, dots, b_n$ of $K$: the ranks of the free part of
  /// the integer homology $H_k (K; ZZ)$. A topological invariant, metric-free.
  ///
  /// $b_0$ counts connected components, $b_1$ independent loops, and so on.
  pub fn betti_numbers(&self) -> Vec<usize> {
    // rank diff_k for k in 0..=n+1; diff_0 and diff_(n+1) map to/from the zero
    // space and so have rank 0.
    let ranks: Vec<usize> = (self.dim() + 1)
      .range_inclusive()
      .map(|k| self.integral_boundary(k).rank())
      .collect();
    self
      .dim()
      .range_inclusive()
      .map(|k| self.nsimplices(k) - ranks[k.index()] - ranks[(k + 1).index()])
      .collect()
  }

  /// The k-th Betti number $b_k = dim H_k (K; ZZ)$.
  pub fn betti_number(&self, grade: impl Into<Dim>) -> usize {
    let grade = grade.into();
    self.nsimplices(grade)
      - self.integral_boundary(grade).rank()
      - self.integral_boundary(grade + 1).rank()
  }

  /// The Euler characteristic $chi = sum_k (-1)^k n_k = sum_k (-1)^k b_k$.
  ///
  /// The two forms agree by Euler--Poincaré. The first is what is computed, and
  /// their equality is an exact cross-check on the Betti numbers.
  pub fn euler_characteristic(&self) -> i64 {
    self
      .dim()
      .range_inclusive()
      .map(|k| {
        let n = self.nsimplices(k) as i64;
        if k.index() % 2 == 0 { n } else { -n }
      })
      .sum()
  }

  /// The $k$-th relative Betti number $b_k (K, partial K) = dim H_k (K, partial K)$,
  /// the dimension of the relative homology of the pair.
  ///
  /// Computed on the relative chain complex $C_(K, partial K) = C_(K) slash
  /// C_(partial K)$, generated by the interior simplices. Its boundary operator is
  /// $partial_k$ with the boundary rows and columns struck out. On a closed manifold
  /// ($partial K = nothing$) it coincides with [`Self::betti_number`].
  ///
  /// This is the rank of the relative homology $H_k (K, partial K)$, dual to the
  /// absolute [`Self::betti_number`]. Computed exactly from the
  /// incidence, so it needs no orientability assumption (unlike the
  /// Poincaré--Lefschetz shortcut $b_k (K, partial K) = b_(n - k) (K)$). Metric-free.
  pub fn relative_betti_number(&self, grade: impl Into<Dim>) -> usize {
    let grade = grade.into();
    let interior = self.interior_selection(grade);
    interior.len() - self.relative_boundary_rank(grade) - self.relative_boundary_rank(grade + 1)
  }

  /// $rank$ of the relative boundary operator $partial_k: C_k (K, partial K) ->
  /// C_(k-1) (K, partial K)$: the boundary simplices struck from both the columns
  /// (domain) and the rows (codomain).
  fn relative_boundary_rank(&self, grade: Dim) -> usize {
    self
      .integral_boundary(grade)
      .submatrix(
        &self.interior_selection(grade - 1),
        &self.interior_selection(grade),
      )
      .rank()
  }
}

impl Complex {
  /// Representative cycles whose classes are a basis of the free part of
  /// $H_k (K; ZZ)$, one [`Chain`] per Betti number $b_k$.
  ///
  /// Each generator is a k-cycle, $partial_k z = 0$. Its class generates a
  /// $ZZ$-summand of $H_k$, and the $b_k$ classes are independent modulo
  /// boundaries. For $k = 0$ these are one vertex per connected component; for
  /// $k = 1$, loops around the holes. At the top grade of a closed manifold, the
  /// fundamental class.
  ///
  /// The subquotient $ker partial_k slash "im" partial_(k+1)$ is computed by the
  /// shared `quotient_generators` routine, where the caveats live: these are
  /// representatives chosen by the elimination order and never minimizers, and
  /// they span the free part over $QQ$ without necessarily generating its
  /// integral lattice.
  pub fn homology_generators(&self, grade: impl Into<Dim>) -> Vec<Chain> {
    let grade = grade.into();
    quotient_generators(
      &self.integral_boundary(grade),
      &self.integral_boundary(grade + 1),
    )
    .into_iter()
    .map(|cycle| Chain::from_vec(grade, cycle))
    .collect()
  }

  /// Representative cycles of a basis of the free part of the relative homology
  /// $H_k (K, partial K; ZZ)$, one per
  /// [`relative_betti_number`](Self::relative_betti_number).
  ///
  /// The relative chains are $C_k (K) slash C_k (partial K)$, generated by the
  /// interior simplices, so the relative complex is the chain complex on the
  /// interior selection and a class is written back out as a full-length chain
  /// by extension by zero. A relative cycle is one whose boundary lies in
  /// $partial K$, not one whose boundary vanishes.
  ///
  /// The Kronecker dual of [`Self::relative_cohomology_generators`], and the
  /// cycles whose periods pin the relative harmonic basis.
  pub fn relative_homology_generators(&self, grade: impl Into<Dim>) -> Vec<Chain> {
    let grade = grade.into();
    let interior = self.interior_selection(grade);
    let outgoing = self
      .integral_boundary(grade)
      .submatrix(&self.interior_selection(grade - 1), &interior);
    let incoming = self
      .integral_boundary(grade + 1)
      .submatrix(&interior, &self.interior_selection(grade + 1));

    quotient_generators(&outgoing, &incoming)
      .into_iter()
      .map(|cycle| Chain::from_vec(grade, interior.scatter(&cycle)))
      .collect()
  }
}
