//! Integer simplicial homology of the complex.
//!
//! The Betti numbers $b_k = dim H_k (K; ZZ)$ of the chain complex
//!
//! $dots.c ->^(diff_(k+1)) C_k ->^(diff_k) C_(k-1) ->^(diff_(k-1)) dots.c$
//!
//! read off the ranks of the (integer) boundary operators:
//!
//! $b_k = dim ker diff_k - rank diff_(k+1) = n_k - rank diff_k - rank diff_(k+1)$,
//!
//! with $n_k$ the number of k-simplices. Metric-free (invariant 5): homology is
//! a topological invariant, a function of the incidence alone.
//!
//! Everything here is exact, over $ZZ$ and $QQ$ rather than over $RR$ with a
//! tolerance, and the arithmetic that makes it so is
//! the crate-internal exact integer linear algebra. The full torsion of $H_k (K; ZZ)$
//! is not recovered: it is invisible to the de Rham / Hodge side of the
//! library, which lives over $RR$, so only the free rank is returned.
//!
//! [`cohomology`](super::cohomology) is the same computation on the transposed
//! incidence.

use super::{chain::Chain, complex::Complex};
use crate::Dim;
use crate::linalg::exact::quotient_generators;

impl Complex {
  /// The Betti numbers $b_0, dots, b_n$ of $K$: the ranks of the free part of
  /// the integer homology $H_k (K; ZZ)$. A topological invariant, metric-free.
  ///
  /// $b_0$ counts connected components, $b_1$ independent loops, and so on.
  pub fn betti_numbers(&self) -> Vec<usize> {
    // rank diff_k for k in 0..=n+1; diff_0 and diff_(n+1) map to/from the zero
    // space and so have rank 0.
    let ranks: Vec<usize> = (self.dim() + 1)
      .range_inclusive()
      .map(|k| self.integral_boundary(k).rank())
      .collect();
    self
      .dim()
      .range_inclusive()
      .map(|k| self.nsimplices(k) - ranks[k.index()] - ranks[(k + 1).index()])
      .collect()
  }

  /// The k-th Betti number $b_k = dim H_k (K; ZZ)$.
  pub fn betti_number(&self, grade: impl Into<Dim>) -> usize {
    let grade = grade.into();
    self.nsimplices(grade)
      - self.integral_boundary(grade).rank()
      - self.integral_boundary(grade + 1).rank()
  }

  /// The Euler characteristic $chi = sum_k (-1)^k n_k = sum_k (-1)^k b_k$.
  ///
  /// The two forms agree by Euler--Poincaré. The first is what is computed, and
  /// their equality is an exact cross-check on the Betti numbers.
  pub fn euler_characteristic(&self) -> i64 {
    self
      .dim()
      .range_inclusive()
      .map(|k| {
        let n = self.nsimplices(k) as i64;
        if k.index() % 2 == 0 { n } else { -n }
      })
      .sum()
  }

  /// The $k$-th relative Betti number $b_k (K, diff K) = dim H_k (K, diff K)$,
  /// the dimension of the relative homology of the pair.
  ///
  /// Computed on the relative chain complex $C_(K, diff K) = C_(K) slash
  /// C_(diff K)$, generated by the interior simplices. Its boundary operator is
  /// $diff_k$ with the boundary rows and columns struck out. On a closed manifold
  /// ($diff K = nothing$) it coincides with [`Self::betti_number`].
  ///
  /// This is the rank of the relative homology $H_k (K, diff K)$, dual to the
  /// absolute [`Self::betti_number`]. Computed exactly from the
  /// incidence, so it needs no orientability assumption (unlike the
  /// Poincaré--Lefschetz shortcut $b_k (K, diff K) = b_(n - k) (K)$). Metric-free.
  pub fn relative_betti_number(&self, grade: impl Into<Dim>) -> usize {
    let grade = grade.into();
    let interior = self.interior_selection(grade);
    interior.len() - self.relative_boundary_rank(grade) - self.relative_boundary_rank(grade + 1)
  }

  /// $rank$ of the relative boundary operator $diff_k: C_k (K, diff K) ->
  /// C_(k-1) (K, diff K)$: the boundary simplices struck from both the columns
  /// (domain) and the rows (codomain).
  fn relative_boundary_rank(&self, grade: Dim) -> usize {
    self
      .integral_boundary(grade)
      .submatrix(
        &self.interior_selection(grade - 1),
        &self.interior_selection(grade),
      )
      .rank()
  }
}

impl Complex {
  /// Representative cycles whose classes are a basis of the free part of
  /// $H_k (K; ZZ)$, one [`Chain`] per Betti number $b_k$.
  ///
  /// Each generator is a k-cycle, $diff_k z = 0$. Its class generates a
  /// $ZZ$-summand of $H_k$, and the $b_k$ classes are independent modulo
  /// boundaries. For $k = 0$ these are one vertex per connected component; for
  /// $k = 1$, loops around the holes. At the top grade of a closed manifold, the
  /// fundamental class.
  ///
  /// The subquotient $ker diff_k slash "im" diff_(k+1)$ is computed by the
  /// shared `quotient_generators` routine, where the caveats live: these are
  /// representatives chosen by the elimination order and never minimizers, and
  /// they span the free part over $QQ$ without necessarily generating its
  /// integral lattice.
  pub fn homology_generators(&self, grade: impl Into<Dim>) -> Vec<Chain> {
    let grade = grade.into();
    quotient_generators(
      &self.integral_boundary(grade),
      &self.integral_boundary(grade + 1),
    )
    .into_iter()
    .map(|cycle| Chain::from_vec(grade, cycle))
    .collect()
  }

  /// Representative cycles of a basis of the free part of the relative homology
  /// $H_k (K, diff K; ZZ)$, one per
  /// [`relative_betti_number`](Self::relative_betti_number).
  ///
  /// The relative chains are $C_k (K) slash C_k (diff K)$, generated by the
  /// interior simplices, so the relative complex is the chain complex on the
  /// interior selection and a class is written back out as a full-length chain
  /// by extension by zero. A relative cycle is one whose boundary lies in
  /// $diff K$, not one whose boundary vanishes.
  ///
  /// The Kronecker dual of [`Self::relative_cohomology_generators`], and the
  /// cycles whose periods pin the relative harmonic basis.
  pub fn relative_homology_generators(&self, grade: impl Into<Dim>) -> Vec<Chain> {
    let grade = grade.into();
    let interior = self.interior_selection(grade);
    let outgoing = self
      .integral_boundary(grade)
      .submatrix(&self.interior_selection(grade - 1), &interior);
    let incoming = self
      .integral_boundary(grade + 1)
      .submatrix(&interior, &self.interior_selection(grade + 1));

    quotient_generators(&outgoing, &incoming)
      .into_iter()
      .map(|cycle| Chain::from_vec(grade, interior.scatter(&cycle)))
      .collect()
  }
}

#[cfg(test)]
pub(super) mod test {
  use super::*;
  use crate::Dim;
  use crate::mesher::grid::CartesianTopology;
  use crate::topology::{simplex::Simplex, skeleton::Skeleton};

  use crate::linalg::exact::IntegerMatrix;

  /// A combinatorial 2-sphere: the boundary of a tetrahedron, whose four
  /// triangles are the facets of the 3-simplex.
  ///
  /// $b_2 = 1$, and no coordinates are needed to say so: a sphere is a
  /// combinatorial object here, not a subdivided icosahedron.
  pub(crate) fn two_sphere() -> Complex {
    Complex::from_cells(Skeleton::new(vec![
      Simplex::new(vec![0, 1, 2]),
      Simplex::new(vec![0, 1, 3]),
      Simplex::new(vec![0, 2, 3]),
      Simplex::new(vec![1, 2, 3]),
    ]))
  }

  /// A square annulus: the $3 times 3$ grid with the middle box removed, so
  /// $b_1 = 1$.
  ///
  /// The middle box is named by its index, not by a barycenter: the Kuhn
  /// generator emits `factorial(dim)` cells per box in colex order, so box
  /// $(1, 1)$ of a $3 times 3$ grid is index 4 and its cells are 8 and 9. That
  /// is combinatorics, which is why this test needs no embedding.
  pub(crate) fn annulus() -> Complex {
    let grid = CartesianTopology::cube(2, 3);
    let middle_box = 4;
    let per_box = multiindex::factorial(2);
    let removed = middle_box * per_box..(middle_box + 1) * per_box;
    let cells: Vec<Simplex> = grid
      .cell_skeleton()
      .iter()
      .enumerate()
      .filter(|(i, _)| !removed.contains(i))
      .map(|(_, s)| s.clone())
      .collect();
    Complex::from_cells(Skeleton::new(cells))
  }

  /// A spread of complexes with nontrivial homology across the grades.
  pub(crate) fn test_complexes() -> Vec<Complex> {
    let mut complexes: Vec<Complex> = (1..=3)
      .map(|dim| CartesianTopology::cube(dim, 2).triangulate())
      .collect();
    complexes.push(two_sphere());
    complexes.push(annulus());
    complexes
  }

  /// Whether a chain is a cycle: $diff_k z = 0$.
  fn is_cycle(complex: &Complex, chain: &Chain) -> bool {
    chain.boundary(complex).coeffs().iter().all(|&c| c == 0)
  }

  /// One generator per Betti number, in every grade.
  #[test]
  fn generators_count_matches_betti() {
    for complex in test_complexes() {
      for k in complex.dim().range_inclusive() {
        assert_eq!(
          complex.homology_generators(k).len(),
          complex.betti_number(k)
        );
      }
    }
  }

  /// Every generator is a cycle.
  #[test]
  fn generators_are_cycles() {
    for complex in test_complexes() {
      for k in complex.dim().range_inclusive() {
        for generator in complex.homology_generators(k) {
          assert!(is_cycle(&complex, &generator), "grade {k}");
        }
      }
    }
  }

  /// The generator classes are independent modulo boundaries: appended to the
  /// columns of $diff_(k+1)$ they raise the rank by exactly $b_k$, so no
  /// generator, nor any combination, is itself a boundary.
  #[test]
  fn generators_independent_modulo_boundaries() {
    for complex in test_complexes() {
      for k in complex.dim().range_inclusive() {
        let boundaries = complex.integral_boundary(k + 1);
        let generators = complex.homology_generators(k);

        let mut triplets = boundaries.triplets().to_vec();
        for (g, generator) in generators.iter().enumerate() {
          for (kidx, &coeff) in generator.support() {
            triplets.push((kidx, boundaries.ncols() + g, coeff));
          }
        }
        let augmented = IntegerMatrix::new(
          boundaries.nrows(),
          boundaries.ncols() + generators.len(),
          triplets,
        );
        assert_eq!(
          augmented.rank(),
          boundaries.rank() + complex.betti_number(k),
          "grade {k}"
        );
      }
    }
  }

  /// Euler--Poincaré: the alternating simplex count equals the alternating
  /// Betti sum. A cross-check tying the Betti numbers back to the raw counts.
  #[test]
  fn euler_poincare() {
    for dim in (1..=3usize).map(Dim::from) {
      let topology = CartesianTopology::cube(dim, 2).triangulate();
      let alt_betti: i64 = topology
        .betti_numbers()
        .iter()
        .enumerate()
        .map(|(k, &b)| if k % 2 == 0 { b as i64 } else { -(b as i64) })
        .sum();
      assert_eq!(alt_betti, topology.euler_characteristic(), "dim={dim}");
    }
  }

  /// A cube is contractible: $b_0 = 1$ and all higher Betti numbers vanish.
  #[test]
  fn cube_is_contractible() {
    for dim in (1..=3usize).map(Dim::from) {
      let topology = CartesianTopology::cube(dim, 2).triangulate();
      let expected: Vec<usize> = std::iter::once(1)
        .chain(std::iter::repeat_n(0, dim.index()))
        .collect();
      assert_eq!(topology.betti_numbers(), expected, "dim={dim}");
    }
  }

  /// Poincaré duality on a closed orientable manifold: $b_k = b_(n-k)$. The
  /// 2-sphere realizes it with Betti numbers $(1, 0, 1)$.
  #[test]
  fn sphere_poincare_duality() {
    let topology = two_sphere();
    let betti = topology.betti_numbers();
    let n = topology.dim();
    for k in 0..=n.index() {
      assert_eq!(betti[k], betti[n.index() - k], "k={k}");
    }
    assert_eq!(betti, vec![1, 0, 1]);
  }

  /// Poincaré--Lefschetz duality on the box, an orientable manifold with
  /// boundary: $b_k (K, diff K) = b_(n-k) (K)$. The box is contractible, so the
  /// relative Betti numbers are $1$ at the top grade and $0$ below, the
  /// harmonic dimension of the essential-BC Hodge-Laplace complex, dual to the
  /// natural-BC one which is harmonic only at grade $0$. The relative
  /// [`Complex::relative_betti_number`] is computed independently of duality
  /// (from the incidence), so their agreement is a real cross-check.
  #[test]
  fn box_lefschetz_duality() {
    for dim in (1..=3usize).map(Dim::from) {
      let topology = CartesianTopology::cube(dim, 2).triangulate();
      for k in dim.range_inclusive() {
        assert_eq!(
          topology.relative_betti_number(k),
          topology.betti_number(dim - k),
          "dim={dim}, k={k}"
        );
        assert_eq!(
          topology.relative_betti_number(k),
          usize::from(k == dim),
          "dim={dim}, k={k}"
        );
      }
    }
  }

  /// On a closed manifold ($diff K = nothing$) the relative complex is the full
  /// complex, so relative and absolute Betti numbers coincide. The 2-sphere.
  #[test]
  fn closed_manifold_relative_equals_absolute() {
    let topology = two_sphere();
    for k in topology.dim().range_inclusive() {
      assert_eq!(
        topology.relative_betti_number(k),
        topology.betti_number(k),
        "k={k}"
      );
    }
  }

  /// The relative generators match the relative Betti numbers, are supported in
  /// the interior, and are cycles *relative to* the boundary: $diff z$ is
  /// carried by $diff K$ rather than vanishing.
  #[test]
  fn relative_generators_count_and_support() {
    for complex in test_complexes() {
      for k in complex.dim().range_inclusive() {
        let generators = complex.relative_homology_generators(k);
        assert_eq!(
          generators.len(),
          complex.relative_betti_number(k),
          "grade {k}"
        );
        let interior = complex.interior_selection(k);
        let interior_below = complex.interior_selection(k - 1);
        for generator in &generators {
          assert!(
            generator
              .support()
              .all(|(kidx, _)| interior.position(kidx).is_some()),
            "a relative cycle must vanish on the boundary, grade {k}"
          );
          assert!(
            generator
              .boundary(&complex)
              .support()
              .all(|(kidx, _)| interior_below.position(kidx).is_none()),
            "a relative cycle's boundary must lie in the boundary, grade {k}"
          );
        }
      }
    }
  }

  #[test]
  fn annulus_generator_is_a_loop() {
    let complex = annulus();
    let generators = complex.homology_generators(1);
    assert_eq!(generators.len(), 1);
    let loop_ = &generators[0];
    assert!(is_cycle(&complex, loop_));
    assert!(loop_.support().count() >= 3);
  }
}
