[package]
name = "ddf"
version = "0.1.0"
edition = "2021"

[dependencies]
exterior = { path = "../exterior" }
manifold = { path = "../manifold" }
common = { path = "../common" }

nalgebra = "0.33.2"
nalgebra-sparse = "0.10.0"
