[package]
name = "formoniq"
version = "0.1.0"
edition = "2021"

[dependencies]
whitney = { path = "../whitney" }
exterior = { path = "../exterior" }
manifold = { path = "../manifold" }
common = { path = "../common" }

nalgebra = "0.33.2"
nalgebra-sparse = "0.10.0"

tracing = "0.1.41"
itertools = "0.14.0"
rayon = "1.10.0"
approx = "0.5.1"


[dev-dependencies]
tracing-subscriber = "0.3.19"
#reqwest = { version = "0.12.9", features = ["blocking"] }
