[package]
name = "formoniq"
version = "0.1.0"
edition = "2021"

[dependencies]
whitney = { path = "../whitney" }
exterior = { path = "../exterior" }
manifold = { path = "../manifold" }
multi-index = { path = "../multi-index" }
common = { path = "../common" }

nalgebra = "0.33.2"
nalgebra-sparse = "0.10.0"

tracing = "0.1.40"
itertools = "0.14.0"


[dev-dependencies]
tracing-subscriber = "0.3.18"
#reqwest = { version = "0.12.9", features = ["blocking"] }
